In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/MMLA Datasets/FinMark CSV/customer_transactions_contaminated.csv")

In [ ]:
print("No. of records:", df.shape[0])
print("No. of columns", df.shape[1])

No. of records: 3200
No. of columns 6

In [ ]:
df.head()

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
1,4090ba85-b111-4f75-a792-c777965f5255,2c39b9fe-ff57-4d39-9321-9f5cdf187aa1,2023-04-26,466.14,Health & Beauty,Bank Transfer
2,9223891b-73ff-4d5c-b8ae-13ece82ee28b,f79588dd-3db9-4ffa-97f8-7de0e64259f1,2022-09-23,563.99,Clothing,Debit Card
3,9243eebc-938f-480c-8564-16d503d250de,401c0fc9-60df-4455-ad78-67c132f9897d,2024-04-15,254.44,Automotive,PayPal
4,6e3e8eb8-bc0f-4ffe-9f74-5d5efec9502f,2034aebc-8280-4254-a667-92bcd1c2be4f,2024-06-03,590.52,Home & Garden,Bank Transfer

In [ ]:
df.tail()

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
3195,59f8afe5-173b-4e52-b641-f98183f1a891,3121df10-58e5-4ed4-a05c-b1f12df6bcc7,2023-01-18,892.44,Home & Garden,Bank Transfer
3196,16d0b561-279d-4da9-9aa8-8c5906dff79a,dff4f636-2c55-4237-8c55-efb15b05949b,2024-02-13,431.64,Health & Beauty,Credit Card
3197,34e3f558-622e-4d6b-8d5d-07ab632e1b95,db0a4640-ea96-4fcd-989b-b71ba767529c,2022-12-26,NaN,Home & Garden,PayPal
3198,d83178cf-653d-435c-a7e8-880361dec6e7,89a1c0bc-4d49-4913-bb0f-26bd56b46a34,2022-09-26,343.46,Health & Beauty,Debit Card
3199,d64b0c8d-1831-4b29-baa2-08c4d5c3a0f9,6c47f481-3a5c-49bc-ab1d-2b198394b2e8,2023-06-20,NaN,Electronics,Debit Card

In [ ]:
df.describe()

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
count,3200,3200,3200,2896,2901,3200
unique,1871,3000,808,2603,5,4
top,49f06ea9-4ae5-4ce5-98ce-d2c2f6f15cbd,a0edadfa-7b00-45ab-bd1d-aceb2c659c67,2023-10-19,-100,Clothing,Debit Card
freq,7,2,13,39,598,809

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       3200 non-null   object
 1   TransactionID    3200 non-null   object
 2   TransactionDate  3200 non-null   object
 3   Amount           2896 non-null   object
 4   ProductCategory  2901 non-null   object
 5   PaymentMethod    3200 non-null   object
dtypes: object(6)
memory usage: 150.1+ KB

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 185

In [ ]:
duplicates = df[df.duplicated(keep=False)]
display(duplicates)

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
9,474f9233-0616-431b-b3e9-a6feabe68abb,f8bde21a-7a6b-41f6-ac39-eeb77640fa9b,2023-06-15,149.39,Clothing,Debit Card
16,54b3556e-e480-41a2-9dcd-7da1d91655aa,c181a599-fcc7-4f9b-b618-783684e0fd24,2023-03-06,861.39,Clothing,Bank Transfer
36,9560ed71-7a04-4cd9-a576-b622c5690487,ad529898-c1b5-4fe7-b30b-a9f19c666386,2024-05-31,833.48,Automotive,Bank Transfer
45,d3493edf-9847-46ef-b400-7063b54bcf63,6fa36483-8ac7-4af8-9cc7-e0607673f331,2022-07-15,119.65,Clothing,PayPal
...,...,...,...,...,...,...
3195,59f8afe5-173b-4e52-b641-f98183f1a891,3121df10-58e5-4ed4-a05c-b1f12df6bcc7,2023-01-18,892.44,Home & Garden,Bank Transfer
3196,16d0b561-279d-4da9-9aa8-8c5906dff79a,dff4f636-2c55-4237-8c55-efb15b05949b,2024-02-13,431.64,Health & Beauty,Credit Card
3197,34e3f558-622e-4d6b-8d5d-07ab632e1b95,db0a4640-ea96-4fcd-989b-b71ba767529c,2022-12-26,NaN,Home & Garden,PayPal
3198,d83178cf-653d-435c-a7e8-880361dec6e7,89a1c0bc-4d49-4913-bb0f-26bd56b46a34,2022-09-26,343.46,Health & Beauty,Debit Card
3199,d64b0c8d-1831-4b29-baa2-08c4d5c3a0f9,6c47f481-3a5c-49bc-ab1d-2b198394b2e8,2023-06-20,NaN,Electronics,Debit Card

In [ ]:
duplicates = df[df.duplicated(keep=False)].sort_values(
    by=["CustomerID", "TransactionID"]
)

display(duplicates)

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
1769,00115fc0-f155-42cd-ba68-58aab67b3360,dbb294f9-9197-48a3-ac56-1b5b13c71388,2023-02-27,153.89,Electronics,Credit Card
3044,00115fc0-f155-42cd-ba68-58aab67b3360,dbb294f9-9197-48a3-ac56-1b5b13c71388,2023-02-27,153.89,Electronics,Credit Card
2935,015006df-480b-4c0d-9a6a-550691817c48,59624c48-19b4-4ddd-b6e4-033681b2dd0e,2024-03-23,986.3,Health & Beauty,Credit Card
3144,015006df-480b-4c0d-9a6a-550691817c48,59624c48-19b4-4ddd-b6e4-033681b2dd0e,2024-03-23,986.3,Health & Beauty,Credit Card
1485,030c85eb-9872-47e3-83ca-0ac4af613294,c889629e-2cbf-49c0-b0da-1242aa4ff08a,2024-05-24,325.16,Health & Beauty,PayPal
...,...,...,...,...,...,...
3115,fdb81781-8071-4364-b074-dacc53de5284,67fe8c82-72f5-4acd-8e6b-70059bef1f6c,2024-04-02,552.37,NaN,PayPal
1279,fe5c7c84-2e6a-4e3d-bf6b-d2b783d13dc1,3a5bbaad-6b7d-4ce5-9eef-a5d6827d4bed,2022-10-13,865.95,Automotive,Bank Transfer
3032,fe5c7c84-2e6a-4e3d-bf6b-d2b783d13dc1,3a5bbaad-6b7d-4ce5-9eef-a5d6827d4bed,2022-10-13,865.95,Automotive,Bank Transfer
740,fe652a6b-df5d-4a14-99e1-3d1bc3d4aba9,f1f2aee9-be7d-429c-96c8-7202c6439315,2024-06-17,507.96,Home & Garden,Bank Transfer
3051,fe652a6b-df5d-4a14-99e1-3d1bc3d4aba9,f1f2aee9-be7d-429c-96c8-7202c6439315,2024-06-17,507.96,Home & Garden,Bank Transfer

In [ ]:
df = df.drop_duplicates()

In [ ]:
print("Duplicates:", df.duplicated().sum())
print("Records remaining:", len(df))

Duplicates: 0
Records remaining: 3015

In [ ]:
missing_values = df.isnull().sum()

print(missing_values)

CustomerID           0
TransactionID        0
TransactionDate      0
Amount             283
ProductCategory    282
PaymentMethod        0
dtype: int64

In [ ]:
print(df["Amount"].value_counts().head(20))

Amount
-100      39
Free      30
0         29
368.91     2
987.1      2
482.63     2
592.76     2
36.05      2
272.68     2
667.93     2
474.57     2
771.33     2
508.4      2
244.05     2
154.02     2
50.07      2
628.86     2
175.31     2
64.28      2
129.92     2
Name: count, dtype: int64

In [ ]:
print(df["Amount"].dtype)

object

In [ ]:
numeric_amount = pd.to_numeric(df["Amount"], errors="coerce")

print("Invalid Values:")
print(df.loc[numeric_amount.isna() & df["Amount"].notna(), "Amount"].value_counts())

Invalid Values:
Amount
Free    30
Name: count, dtype: int64

In [ ]:
print("Negative values:", (numeric_amount < 0).sum())
print("Zero values:", (numeric_amount == 0).sum())

Negative values: 40
Zero values: 30

In [ ]:
negative_amounts = df[df["Amount"].astype(str).str.strip() == "-100"]

display(negative_amounts)

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
274,e6f4ae74-d58d-4770-8ebc-89c1f8778a6d,814d25d8-690b-45bb-96c9-b7a3e92a61db,2023-01-25,-100,NaN,PayPal
319,b91999f9-b7ed-4da4-a285-1dafae98e21d,fb908e24-4c1e-4e24-a1b0-62465fa0515c,2024-03-22,-100,Health & Beauty,Debit Card
334,a800ccba-e1ca-4f52-ad9f-14f3432699c9,487ecd9b-57c8-447c-a2a8-e55477ba0d6d,2023-09-25,-100,Clothing,Bank Transfer
381,a94e3f55-2f0e-432e-8706-9815c4371376,f53b16b4-d042-44ca-a073-4acdd546b519,2024-01-06,-100,Home & Garden,PayPal
447,ca645b4d-28a4-42ec-99a7-8000d38bf2e0,f35cadbe-6ae1-427d-8b41-5749cc1173e6,2023-06-18,-100,Electronics,Bank Transfer
449,a7c29c33-e968-4d84-82cd-1269ed1e7c1e,77954a26-9a04-4806-b525-7f33f554d255,2022-09-11,-100,Home & Garden,Credit Card
476,ac6b4d61-3d14-4362-b226-8c0c5786d6df,1074d2cf-a7d5-4ebd-baa9-4660b2df5ec8,2023-07-17,-100,Health & Beauty,Credit Card
500,ffe9a403-ac25-4aad-a809-ac9687ff3fcd,c59819cc-cf92-4929-ad22-ef3435187be9,2023-04-01,-100,Automotive,Bank Transfer
563,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,03/04/2023,-100,Electronics,Debit Card
652,f56e56b7-bbde-455c-b570-61cd2005b4e4,f99eba1f-0092-4487-b753-9fce61e0ca26,2023-02-05,-100,Automotive,PayPal
702,ab87ecef-f7ea-49b0-8c50-c31442ad5c46,64138a25-3a63-41fd-aa81-f74231597191,2022-12-04,-100,Home & Garden,Debit Card
727,db10c135-1080-4fce-b653-d5a5fb572fa8,adbe44db-78ec-408b-80ad-e119e0f58123,2024-05-13,-100,Home & Garden,Credit Card
1129,6b6cd86a-d0af-48ab-ada5-e596f726cffa,eed1a5a0-4a6b-40b1-9c43-abfeff1a7735,2024-06-02,-100,Clothing,Credit Card
1240,03fac2e6-f130-4cf6-b8b8-2f147c2fe60a,6f57c9c3-0c11-4d34-9392-08eb6b91fd0e,2024-05-21,-100,Home & Garden,Debit Card
1241,799943c7-3b71-4f24-9b16-c2fcaf9b3871,09b0508b-a705-48d0-8594-5b7d85d024eb,2022-11-08,-100,Automotive,PayPal
1263,38d746bd-c227-416a-aa28-610ffd379e58,db154379-42a3-4ae0-a4d3-29c53226f8a1,2024-06-22,-100,Electronics,Bank Transfer
1577,7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc,6cfe5871-8524-4d81-abaa-a54fdd3c873d,2023-06-11,-100,Automotive,PayPal
1705,f102f93b-f32c-41d3-adcc-25e02a67c34f,084e56a5-99eb-48df-801e-bda9cd5ff591,2023-11-03,-100,Electronics,PayPal
1808,28097c07-e810-4e64-8eae-bff2abd81bc1,ab723d41-abdc-412b-b3b9-68796b746a8e,2023-07-11,-100,Automotive,Credit Card
1907,b7b84b81-c61b-4f23-b3db-b18010484122,d7740397-087b-49bb-bf31-2a50ca0e70f6,2023-03-14,-100,Clothing,PayPal
1942,e7e5e8fe-5fdd-43e6-92e1-5ea3e399486e,5b6352cf-da83-46ab-a0ff-79da90691392,2023-12-25,-100,Electronics,PayPal
1994,d968cee0-3524-42d4-a0f7-5fe6e8284890,0705d2f0-ab60-4664-b65e-971e3e2c27d5,2023-10-09,-100,Clothing,Debit Card
2191,1f5c50db-9c55-4bbc-8a93-c7994a7bb3d3,4b4ddbb6-36cf-44eb-8e7a-b27c529f1cff,2022-12-20,-100,Automotive,Bank Transfer
2239,448245da-3a0b-4f52-a40f-a25ca0a2fb6b,ddebc095-ed7c-4c6e-87d8-e7f00c0b50c6,2023-01-24,-100,Home & Garden,Credit Card
2319,21098ed8-fac6-4727-8f0c-953365b6c837,c100f59f-61aa-4c82-825e-dedfde73917b,2023-02-14,-100,Home & Garden,PayPal
2443,ce3f403f-b955-4364-ae22-bf351381e01f,0e5b9cc6-9b94-45fc-8bf8-b8031cd987a7,2023-04-21,-100,Home & Garden,Bank Transfer
2467,0e678ba1-7b5f-46aa-8b5a-6dc1190373be,33ce68ea-42c4-48eb-8631-c8f611d2a330,2023-03-01,-100,Clothing,Debit Card
2480,eca27290-1c40-48c6-b0a5-8afedd9be099,341e25ef-3062-484d-8d07-cc4e0ddb996f,2022-08-02,-100,Clothing,Credit Card
2516,7e280186-770e-4c4a-b330-73dd471f956a,35faff4a-1bf8-4b42-a7ac-847b4970f4b8,2023-09-19,-100,Home & Garden,Bank Transfer
2522,bfe55c3b-668e-485d-9476-670acd50b12b,52bb2a8d-acab-45f9-9817-6e9fe7567824,2024-05-03,-100,Health & Beauty,Debit Card
2621,8d435ee0-fa33-4553-880a-e26511ac3921,c0d0ae2b-eb99-49e5-89ad-0624ad136056,2023-03-27,-100,Home & Garden,Bank Transfer
2737,c56a1423-e1b0-45c1-974a-55f5fa029c88,b401a1e8-6cc3-4ab6-bff4-c41a3847329a,2024-05-31,-100,Electronics,PayPal
2910,f35c6e3f-2fac-4b7a-b713-863a0a37160c,e2d7a068-e92e-407a-8d48-4cf8da4a4c2c,2024-03-12,-100,Health & Beauty,PayPal
3012,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,-100,Health & Beauty,Debit Card
3038,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,2024-04-18,-100,Automotive,Credit Card
3050,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,-100,NaN,Bank Transfer
3073,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,-100,Electronics,Bank Transfer
3123,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,-100,Clothing,Bank Transfer
3177,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100,Health & Beauty,Credit Card

In [ ]:
free_amounts = df[df["Amount"].astype(str).str.strip() == "Free"]

display(free_amounts)

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
5,3eccdcf9-e8ce-4e44-9f62-8bef88e70672,78dfb45e-16e0-4ecc-8f67-f2e210c31c3e,2024-04-07,Free,NaN,Credit Card
59,04b0cd53-29ca-48ef-b4b7-9520a2939288,611876da-a85d-4969-8d84-7a9cf8ddbf59,2023-09-02,Free,Automotive,PayPal
161,56058449-276a-417e-b6c6-f8853b1d2659,b7e042d1-7ad0-430d-8984-82dfa9048a64,2024-05-29,Free,NaN,Credit Card
250,7e3256b2-49d1-419e-a30c-8504f446e64e,cd29e076-8de9-416b-bc0e-fecb61c8baff,2023-10-27,Free,Home & Garden,Credit Card
432,ccf4d58b-5087-45c8-a8f8-bb99be9a13d1,36d14454-fb95-4b19-a574-e137ddb55528,2024-02-09,Free,Electronics,Credit Card
755,1fbbc3ad-d48f-4e64-9ef7-4e58277af29a,a7e2384a-9efb-4519-aa01-683daa01d6e9,2024-04-14,Free,Electronics,Debit Card
764,e06f0e16-8e48-483b-b103-9f105b139ca8,983162b4-b06e-41d3-956c-2c3eed3cf6c4,2023-08-18,Free,Home & Garden,Debit Card
786,481bcc62-9dcb-4766-bbdd-79f5554d73f8,f9cdb10b-2e40-4df2-a7c4-3614151587b6,2024-04-11,Free,Electronics,PayPal
853,77280a9d-3fc9-4140-bc4e-b85cd5c7a8b1,519f279a-5e5d-4a98-8a28-6c04e66c62b7,2022-09-26,Free,Electronics,PayPal
854,68afa4cc-e2d5-4150-b358-2e14e7508721,87459f1a-8873-450f-8b7d-ac4c7b41ba90,2023-07-20,Free,Electronics,Bank Transfer
1008,8f440758-f8ac-44ee-9f83-51d9bde6d101,49fd3057-88b4-4896-bf5b-2e501b76df5b,2022-07-02,Free,Electronics,Credit Card
1041,2de49c7c-32ae-4ba8-b058-622a090d7094,8b7c550f-4acc-4333-a144-cc4d75aa8d1a,2024-01-24,Free,Home & Garden,PayPal
1179,9f9f72a5-0ec8-4847-ab9c-d7694d86f53a,a6ea336a-46dd-480a-9dff-232bc67e956c,2024-02-11,Free,Home & Garden,Credit Card
1214,13b1dad8-724d-45e8-9ecd-912d09e4931c,46dbc70f-3b20-4e27-8af2-a58801d78774,2023-02-06,Free,Health & Beauty,Credit Card
1215,4231fa1b-073c-4bf2-94d6-22dd9dd33929,66f81587-2823-40f4-9f67-a51c4fb3b603,2023-09-25,Free,Clothing,Debit Card
1267,b791d365-bf14-43ae-9939-aabd2c982866,200d7d2e-ec9e-4152-865e-0e4099006397,2023-08-21,Free,Home & Garden,Debit Card
1310,321adc94-8a35-4998-bc17-0cacc00988f4,8c8b85f2-5e6e-457a-899d-6c4b392d2239,2023-08-22,Free,Home & Garden,Credit Card
1460,ee802844-8070-4699-b60d-3568a7d306b6,3e221ee0-a001-4fa5-ba4e-c3ca8f381ee8,2022-07-20,Free,Home & Garden,Bank Transfer
1534,99462720-beca-4890-852e-79d16990f055,fc58b548-8913-4fb9-a952-9f6edee9d011,2023-10-07,Free,Automotive,PayPal
1748,69c0971b-1c85-429a-aa61-496f9c0a4410,00816003-b5ea-4564-a8f6-d25b9e44bbcf,2023-04-02,Free,Clothing,PayPal
1777,f3dc5fd3-b7ab-4996-ad89-1954cc27849e,5f18cb21-0ca3-451c-ac1d-4c1dfef1a9a4,2022-07-29,Free,Clothing,Debit Card
1882,c5dfebb9-5891-4a1d-a50c-a6851dad85cf,635c8590-2515-4c9b-97d9-8bfd0e909d8c,2023-10-13,Free,Electronics,Bank Transfer
2121,28a886bd-0c98-4532-bbb3-4ba77a9ee275,3044af7d-d422-474b-9b9b-687880505ffe,2023-05-09,Free,Clothing,Credit Card
2556,8f7a9b25-42c2-4cdd-8b0c-b66e1ca3e78a,542e0ad1-07e0-4e9e-aa47-927c93ec08ae,2022-07-09,Free,Electronics,Bank Transfer
2608,309a0ae4-8bd2-4440-935a-44f504c66431,5cb46da7-d495-45ba-8a58-23944fca1c31,2024-04-11,Free,Clothing,Credit Card
2630,32cef811-93ec-48b4-9fa5-e1174156e8cc,cd82917c-279f-4cc0-9763-caf8589afba1,2024-02-21,Free,Clothing,Bank Transfer
2632,80afb9fd-6751-40b6-b4ff-f3c08e12d4c9,aa210434-2df7-48e6-acc6-c83c8cc05425,2023-01-17,Free,Health & Beauty,PayPal
2707,a7b667f7-d6c7-4fc6-b6d9-bcdeea32297c,bbb31735-10e0-405a-8f39-c47df3cb5310,2022-12-12,Free,Clothing,PayPal
2794,7d0dffb7-45b1-456f-b4fa-512b3d1ba9ce,de784b38-50b9-4cc0-b919-395195cae216,2022-11-08,Free,Health & Beauty,Debit Card
3005,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,Free,Health & Beauty,PayPal

In [ ]:
df = df.copy()

In [ ]:
df["Amount"] = df["Amount"].replace("Free", 0)
df["Amount"] = pd.to_numeric(df["Amount"], errors="coerce")

In [ ]:
df.loc[df["Amount"] == -100, "Amount"] = pd.NA

In [ ]:
print("Amount data type:", df["Amount"].dtype)
print("Invalid values:", df["Amount"].isna().sum())
print("Negative values:", (df["Amount"] < 0).sum())

Amount data type: float64
Invalid values: 323
Negative values: 0

In [ ]:
median_amount = df["Amount"].median()

print(median_amount)

498.015

In [ ]:
df["Amount"] = df["Amount"].fillna(median_amount)

In [ ]:
print("Missing:", df["Amount"].isna().sum())
print("Minimum Amount value:", df["Amount"].min())
print("Median:", df["Amount"].median())

Missing: 0
Minimum Amount value: 0.0
Median: 498.015

In [ ]:
df["ProductCategory"] = df["ProductCategory"].fillna("Undetermined")

In [ ]:
print("Missing values:", df["ProductCategory"].isna().sum())
print("\nProductCategory values:")
print(df["ProductCategory"].value_counts())

Missing values: 0

ProductCategory values:
ProductCategory
Clothing           571
Electronics        564
Automotive         540
Home & Garden      530
Health & Beauty    528
Undetermined       282
Name: count, dtype: int64

In [ ]:
print(df["TransactionDate"].head(20))

0     2024-05-15
1     2023-04-26
2     2022-09-23
3     2024-04-15
4     2024-06-03
5     2024-04-07
6     2024-01-12
7     2023-03-10
8     2024-01-26
9     2023-06-15
10    2023-06-01
11    2024-03-09
12    2022-11-06
13    2024-01-28
14    2023-11-08
15    2022-07-24
16    2023-03-06
17    2024-04-17
18    2023-05-02
19    2023-12-27
Name: TransactionDate, dtype: object

In [ ]:
print(df["TransactionDate"].tail(20))

2995    2024-01-07
2996    2024-01-14
2997    2022-12-18
2998    2023-04-06
2999    2024-04-10
3005    2022-08-23
3012    2023-06-01
3038    2024-04-18
3048    2023-05-10
3050    2023-09-30
3073    2023-05-10
3094    2023-02-04
3105    27/03/2024
3113    2024-03-05
3123    2023-05-17
3153    2023-12-05
3157    10/08/2022
3164    20/07/2022
3174    2023-10-09
3177    2023-09-22
Name: TransactionDate, dtype: object

In [ ]:
df["TransactionDate"] = pd.to_datetime(
    df["TransactionDate"],
    format="%Y-%m-%d",
    errors="coerce"
)

In [ ]:
print( df["TransactionDate"].dtype)
print("Invalid:", df["TransactionDate"].isna().sum())

datetime64[ns]
Invalid: 98

In [ ]:
original_df = pd.read_csv("/content/drive/MyDrive/MMLA Datasets/FinMark CSV/customer_transactions_contaminated.csv")

invalid_dates = original_df[
    pd.to_datetime(
        original_df["TransactionDate"],
        format="%Y-%m-%d",
        errors="coerce"
    ).isna()
]

print("Invalid values:", len(invalid_dates))
print(invalid_dates["TransactionDate"].value_counts())

Invalid values: 98
TransactionDate
30/05/2023    3
24/05/2023    2
12/06/2024    2
17/10/2023    2
27/03/2024    2
             ..
20/01/2024    1
10/05/2024    1
01/07/2023    1
10/08/2022    1
20/07/2022    1
Name: count, Length: 92, dtype: int64

In [ ]:
df["TransactionDate"] = original_df["TransactionDate"].astype("string").str.strip()

parsed_dates = pd.to_datetime(
    df["TransactionDate"],
    format="%Y-%m-%d",
    errors="coerce"
)

mask = parsed_dates.isna()

parsed_dates.loc[mask] = pd.to_datetime(
    df.loc[mask, "TransactionDate"],
    format="%d/%m/%Y",
    errors="coerce"
)

df["TransactionDate"] = parsed_dates

In [ ]:
print("TransactionDate data type:", df["TransactionDate"].dtype)
print("Invalid date values:", df["TransactionDate"].isna().sum())

TransactionDate data type: datetime64[ns]
Invalid date values: 0

In [ ]:
print("FINAL DATASET CHECK")

print("\nShape:")
print(df.shape)

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

FINAL DATASET CHECK

Shape:
(3015, 6)

Data types:
CustomerID                 object
TransactionID              object
TransactionDate    datetime64[ns]
Amount                    float64
ProductCategory            object
PaymentMethod              object
dtype: object

Missing values:
CustomerID         0
TransactionID      0
TransactionDate    0
Amount             0
ProductCategory    0
PaymentMethod      0
dtype: int64

Duplicate rows:
0

In [ ]:
Customer_Transaction_Cleaned_Dataset = "Customer_Transaction_Cleaned_Dataset.csv"

df.to_csv(Customer_Transaction_Cleaned_Dataset, index=False)

print("Save as:", Customer_Transaction_Cleaned_Dataset)

Save as: Customer_Transaction_Cleaned_Dataset.csv

In [ ]:
from google.colab import files

files.download("Customer_Transaction_Cleaned_Dataset.csv")