In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/MMLA Datasets/FinMark CSV/social_media_interactions_contaminated.csv")

In [ ]:
print("No. of records:", df.shape[0])
print("No. of Columns:", df.shape[1])

No. of records: 3200
No. of Columns: 6

In [ ]:
df.head()

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
0,2dcb9523-356b-40b2-a67b-1f27797de261,e5d15761-d0a7-4329-89e3-79a892c56097,2023-07-11,NaN,Comment,NaN
1,e12c37b3-7d4d-472f-9fd8-0df2cb3001aa,02f9f376-70ae-4fcd-9070-1db977939948,2023-07-06,Twitter,Share,NaN
2,08a911a3-65e6-4f5d-a6a1-ae7ddcbe28a2,a83fa04c-f109-4f24-8ce1-2078154f6a1c,2024-05-24,Instagram,Comment,Neutral
3,efdfdfc9-5dbb-4478-911a-101a390a0285,28a69c4b-a2e4-4c74-a130-1132d7733fdf,2023-11-01,Instagram,Like,Neutral
4,ca1e90f6-0e5f-492e-ab92-252ff540da18,d9d1c6f8-5e15-4738-b52b-13c2982420cc,2023-07-08,Instagram,Like,NaN

In [ ]:
df.tail()

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
3195,8d8fe8bd-2009-4a15-be37-83dba3cef447,2212803c-4a00-4263-bae5-aaaff6d6bdb1,2023-08-30,Instagram,Like,Neutral
3196,1756838b-8368-4852-b4a5-32a23643a3dd,2f50ca57-f930-4d3e-ae08-9f3b26c7f148,2024-06-16,Facebook,Like,Neutral
3197,eb8bb3ce-e182-4a9c-8084-c55c738815e1,ee2c3d14-248c-48b0-aa80-4ea97e449bf8,2023-12-22,Instagram,Comment,Negative
3198,a5d08a95-9dba-4e3d-b997-1cfdde6a89ef,e77a8713-fdc7-4f71-85f8-9cd88cca0c42,2023-11-01,Twitter,Share,Positive
3199,f8146100-569d-4cda-9d64-88c6ad98de5f,454a0b90-d1bb-437d-ad50-ef01821fbf0a,2024-06-20,Instagram,Like,Neutral

In [ ]:
print(df.columns)

Index(['CustomerID', 'InteractionID', 'InteractionDate', 'Platform',
       'InteractionType', 'Sentiment'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       3200 non-null   object
 1   InteractionID    3200 non-null   object
 2   InteractionDate  3200 non-null   object
 3   Platform         2889 non-null   object
 4   InteractionType  3200 non-null   object
 5   Sentiment        2871 non-null   object
dtypes: object(6)
memory usage: 150.1+ KB

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 180

In [ ]:
duplicates = df[df.duplicated(keep=False)]

display(duplicates)

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
3,efdfdfc9-5dbb-4478-911a-101a390a0285,28a69c4b-a2e4-4c74-a130-1132d7733fdf,2023-11-01,Instagram,Like,Neutral
30,eb8bb3ce-e182-4a9c-8084-c55c738815e1,ee2c3d14-248c-48b0-aa80-4ea97e449bf8,2023-12-22,Instagram,Comment,Negative
64,58ced86b-155c-45b1-96c4-92e39af3751e,7d7f1f20-150c-491c-9dc3-fe2922a19836,2023-10-10,Instagram,Comment,Negative
71,a7b667f7-d6c7-4fc6-b6d9-bcdeea32297c,39622755-9e00-4107-8ee1-5defd5a5dbab,2023-10-06,Twitter,Like,Neutral
91,47bf3bc6-17a6-4b21-82b5-90f78af4c25c,4eac4bf7-b0ff-4eb9-af31-69b5413a99af,2023-10-19,Instagram,Like,Positive
...,...,...,...,...,...,...
3195,8d8fe8bd-2009-4a15-be37-83dba3cef447,2212803c-4a00-4263-bae5-aaaff6d6bdb1,2023-08-30,Instagram,Like,Neutral
3196,1756838b-8368-4852-b4a5-32a23643a3dd,2f50ca57-f930-4d3e-ae08-9f3b26c7f148,2024-06-16,Facebook,Like,Neutral
3197,eb8bb3ce-e182-4a9c-8084-c55c738815e1,ee2c3d14-248c-48b0-aa80-4ea97e449bf8,2023-12-22,Instagram,Comment,Negative
3198,a5d08a95-9dba-4e3d-b997-1cfdde6a89ef,e77a8713-fdc7-4f71-85f8-9cd88cca0c42,2023-11-01,Twitter,Share,Positive
3199,f8146100-569d-4cda-9d64-88c6ad98de5f,454a0b90-d1bb-437d-ad50-ef01821fbf0a,2024-06-20,Instagram,Like,Neutral

In [ ]:
df = df.drop_duplicates()

In [ ]:
print("Duplicate rows:", df.duplicated().sum())
print("Records remaining:", len(df))

Duplicate rows: 0
Records remaining: 3020

In [ ]:
missing_values = df.isnull().sum()

print(missing_values)

CustomerID           0
InteractionID        0
InteractionDate      0
Platform           291
InteractionType      0
Sentiment          309
dtype: int64

In [ ]:
print("\nColumns with missing values:")
print(missing_values[missing_values > 0])

Columns with missing values:
Platform     291
Sentiment    309
dtype: int64

In [ ]:
df['Platform'].unique()

array([nan, 'Twitter', 'Instagram', 'Facebook'], dtype=object)

In [ ]:
df['Platform'].value_counts(dropna=False)

Platform
Instagram    921
Twitter      917
Facebook     891
NaN          291
Name: count, dtype: int64

In [ ]:
df['Sentiment'].unique()

array([nan, 'Neutral', 'Positive', 'Negative', 'Very Negative',
       'Very Positive'], dtype=object)

In [ ]:
df['Platform'].value_counts(dropna=False)

Platform
Instagram    921
Twitter      917
Facebook     891
NaN          291
Name: count, dtype: int64

In [ ]:
df["Platform"] = df["Platform"].fillna("Undetermined")
df["Sentiment"] = df["Sentiment"].fillna("Undetermined")

In [ ]:
print(df.isnull().sum())

CustomerID         0
InteractionID      0
InteractionDate    0
Platform           0
InteractionType    0
Sentiment          0
dtype: int64

In [ ]:
print(df.dtypes)

CustomerID         object
InteractionID      object
InteractionDate    object
Platform           object
InteractionType    object
Sentiment          object
dtype: object

In [ ]:
print(df["InteractionDate"].head(20))

0     2023-07-11
1     2023-07-06
2     2024-05-24
3     2023-11-01
4     2023-07-08
5     2023-12-18
6     2023-11-15
7     2024-03-29
8     2024-05-02
9     2023-11-18
10    2024-05-28
11    2024-06-27
12    2023-08-31
13    2023-08-27
14    2024-06-10
15    2024-02-12
16    2023-08-18
17    2023-08-17
18    2024-03-28
19    2023-10-08
Name: InteractionDate, dtype: object

In [ ]:
print(df["InteractionDate"].tail(20))

3005    2024-03-20
3017    04/06/2024
3021    17/07/2023
3034    2023-08-12
3040    23/07/2023
3042    2023-10-22
3061    2024-06-04
3084    24/01/2024
3091    2023-12-27
3093    2023-11-30
3120    2023-10-23
3126    2024-02-22
3130    2023-07-19
3141    2024-03-14
3146    17/06/2024
3166    2024-04-30
3170    2024-05-16
3173    2023-12-16
3175    2024-01-28
3194    2024-06-29
Name: InteractionDate, dtype: object

In [ ]:
print(df["InteractionDate"].sample(20, random_state=50))

169     2024-02-07
2496    2024-05-15
222     2023-11-18
2327    2024-04-20
358     2024-04-05
2233    2024-04-25
462     2023-11-10
2088    2024-01-13
288     2023-12-19
2434    15/08/2023
1514    2023-07-03
12      2023-08-31
634     2024-03-28
2750    2023-07-17
1367    2023-07-16
215     2024-06-10
2758    2024-05-17
2879    2023-10-27
1192    2024-05-10
2448    2023-08-13
Name: InteractionDate, dtype: object

In [ ]:
raw_dates = df["InteractionDate"].astype("string").str.strip()

parsed_dates = pd.to_datetime(
    raw_dates,
    format="%Y-%m-%d",
    errors="coerce"
)

mask = parsed_dates.isna()

parsed_dates.loc[mask] = pd.to_datetime(
    raw_dates.loc[mask],
    format="%d/%m/%Y",
    errors="coerce"
)

df["InteractionDate"] = parsed_dates

In [ ]:
print("Invalid dates:", df["InteractionDate"].isna().sum())
print("Data type:", df["InteractionDate"].dtype)

Invalid dates: 0
Data type: datetime64[ns]

In [ ]:
print("FINAL DATASET CHECK")

print("\nShape:")
print(df.shape)

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

FINAL DATASET CHECK

Shape:
(3020, 6)

Data types:
CustomerID                 object
InteractionID              object
InteractionDate    datetime64[ns]
Platform                   object
InteractionType            object
Sentiment                  object
dtype: object

Missing values:
CustomerID         0
InteractionID      0
InteractionDate    0
Platform           0
InteractionType    0
Sentiment          0
dtype: int64

Duplicate rows:
0

In [ ]:
Social_Media_Interactions_Cleaned_Dataset = "Social_Media_Interactions_Cleaned_Dataset.csv"

df.to_csv(Social_Media_Interactions_Cleaned_Dataset, index=False)

print("Save as:", Social_Media_Interactions_Cleaned_Dataset)

Save as: Social_Media_Interactions_Cleaned_Dataset.csv

In [ ]:
from google.colab import files

files.download("Social_Media_Interactions_Cleaned_Dataset.csv")